- name: Enterprise Service and Monitoring Setup
  hosts: all
  become: true
  tasks:
    - name: Download Monitoring tools
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v2.46.0/prometheus-2.46.0.linux-amd64.tar.gz"
        dest: /tmp/prometheus.tar.gz

    - name: Extract Monitoring tools
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt
        remote_src: true

    - name: Move Monitoring tool files
      command:
        cmd: mv /opt/prometheus-2.46.0.linux-amd64 /opt/prometheus
      args:
        creates: /opt/prometheus

    - name: Create Monitoring tool user
      user:
        name: prometheus
        shell: /sbin/nologin

    - name: Set Monitoring Ownership
      file:
        path: /opt/prometheus
        owner: prometheus
        group: prometheus
        state: directory
        recurse: yes

    - name: Configure Monitoring tool as a Service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus Monitoring
          After=network.target

          [Service]
          User=prometheus
          ExecStart=/opt/prometheus/prometheus \
            --config.file=/opt/prometheus/prometheus.yml \
            --storage.tsdb.path=/opt/prometheus/data
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and Enable Monitoring tool
      systemd:
        daemon_reload: true
        name: prometheus
        state: started
        enabled: true
